Args=--initialize-at-build-time=io.micronaut.flyway.StaticResourceProvider,io.micronaut.flyway.StaticResourceProvider$StaticLoadableResource \
     --initialize-at-run-time=sun.security.util.Password$ConsoleHolder \
     -H:+UnlockExperimentalVMOptions \
     -H:+SharedArenaSupport