Args=--initialize-at-build-time=io.micronaut.flyway.StaticResourceProvider,io.micronaut.flyway.StaticResourceProvider$StaticLoadableResource \
     -H:+UnlockExperimentalVMOptions \
     -H:+SharedArenaSupport